---@type NvPluginSpec[]
local plugins = {
  require "configs.overrides.cmpconfig",
  require "configs.overrides.conformconfig",
  require "configs.overrides.gitsigns",
  require "configs.overrides.lspconfig",
  require "configs.overrides.nvimtree",
  require "configs.overrides.telescope",
  require "configs.overrides.treesitter",

  require "configs.avante",
  require "configs.colorizer",
  require "configs.comments",
  require "configs.copilot",
  require "configs.copilotcmp",
  require "configs.crates",
  require "configs.dap",
  require "configs.dap_ui",
  require "configs.dressing",
  require "configs.fugitive",
  require "configs.glslview",
  require "configs.harpoon",
  require "configs.lastplace",
  require "configs.lazygit",
  require "configs.markdown_preview",
  require "configs.multicursors",
  require "configs.noice",
  require "configs.nullls",
  require "configs.oil",
  require "configs.rustaceanvim",
  require "configs.signature",
  require "configs.spider",
  require "configs.snacks",
  require "configs.surround",
  require "configs.targets",
  require "configs.tmuxnavigator",
  require "configs.todocomments",
  require "configs.tsautotag",
}

return plugins
